#!/usr/bin/env bash

# How to create a Drupal site managed by Composer

# See also:
# https://www.lullabot.com/articles/drupal-8-composer-best-practices
# https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md
# https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates

# Create project "example"
cd ~/websites
project=example
COMPOSER_MEMORY_LIMIT=-1 \
    composer create-project drupal/recommended-project my-project "${project}"
cd "${project}"
git init
cp web/example.gitignore .gitignore
rm .editorconfig
git add .gitignore .gitattributes composer.{lock,json}
git commit -m "Initial commit"

# The composer.lock file is important, to get exactly the same versions of all
# packages if you set up your website somewhere else. If you would commit only
# composer.json, composer would download the newest package, making the two
# websites possibly out of sync.

# To update your packages
composer update

# To set up website somewhere else
git clone "${gitDir}"
composer install

# Now make the web folder visible from outside
cd ~http
sudo ln -s ~/websites/example/web/ "${project}"

# Make sure that Apache has the permissions to write in your directory. This has
# the side effect that you don't have permissions to write in the directory
# anymore. Not sure if this is a problem in the future. See also:
# https://serverfault.com/questions/357108/what-permissions-should-my-website-files-folders-have-on-a-linux-webserver
sudo chown -R http:http "${project}"

# Create new database. Following:
# https://www.drupal.org/docs/8/install/step-3-create-a-database#create-a-database-from-the-command-line
mysql -u root -p \
    -e 'CREATE DATABASE db_project CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';

# Optionally create a new user, or use an existing one
mysql -u root -p \
    -e 'CREATE USER user@localhost IDENTIFIED BY "password";'

# Grant permissions to user (note that you will have to use backtics ` around
# the db name, if you use "_" or "%", and you need to use backslash \ before "_"
mysql -u root -p \
    -e 'GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON `db\_project`.* TO "user"@"localhost" IDENTIFIED BY "password";'

# Flush the privileges to make sure the user has active privileges
mysql -u root -p -e "FLUSH PRIVILEGES;"

# Go to the website
# http://localhost/${project}/
# and click through the installer from Drupal
