#!/usr/bin/env bash

# Submit jobs
condor_submit <condor_file>

# A typical condor file looks like this
universe = vanilla
Executable = ./test.py
Requirements = OpSys == "LINUX" && (Arch != "DUMMY" )
request_disk = 10000000
request_memory = 2100
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT_OR_EVICT
Transfer_Input_Files = ./test.py
Output = JOBNAME_$(Cluster).stdout
Error = JOBNAME_$(Cluster).stderr
Log = JOBNAME_$(Cluster).condor
notification = Never
x509userproxy = $ENV(X509_USER_PROXY)
Arguments = blubb
Queue 1

# Watch queues/jobs
condor_q -submitter bschneid

# Kill jobs
condor_rm <job_id>

# If a job is in "held" state, analyze what's wrong
condor_q analyze

# Check user priorities and running jobs
condor_userprio
