#!/usr/bin/env bash

# Some debug tools:

dstat
# Prints out how much network and disk your computer uses each second

strace ./myprog
# Prints every system call your program used; good to get an overall picture of
# what your program is doing, for example, if you want to know what files are
# opened, use
strace -e open -p "$PID"
# Strace slows down the execution of your program by as much as a factor of 50!

opensnoop -p "$PID"
# Tells you what files are opened, it's the same as the strace command above,
# but it doesn't slow down your program; opensnoop needs a relatively new kernel
# feature called eBPF, hence it is not (yet) widely available on servers

perf
# perf is a very handy tool that can do various things. Type perf to get its
# options. One example would be perf top
