#!/usr/bin/env bash

# The set options that you always use, but always forget what they are for:

set -e
# Abort script at first error, when a command exits with non-zero status (except
# in until or while loops, if-tests, list constructs)

set -u
# Attempt to use undefined variable outputs error message, and forces an exit

set -f
# Filename expansion (globbing) disabled

set -o pipefail
# Causes a pipeline to return the exit status of the last command in the pipe
# that returned a non-zero return value.

# Good resource:
# https://www.tldp.org/LDP/abs/html/options.html
